# --- Backend ---
backend = "xrender";

# --- VSync ---
# تفعيل المزامنة لمنع الـ tearing
vsync = true;

# --- الحواف الدائرية ---
# ملحوظة: تأكد أنك تستخدم نسخة picom-jonaburg-git من AUR لدعمها
corner-radius = 12;
rounded-corners-exclude = [
  "class_g = 'i3bar'"
  #"window_type = 'popup_menu'",
  #"window_type = 'dropdown_menu'"
];

# --- الشفافية (Opacity) ---
# النافذة النشطة 100%، غير النشطة 90%
inactive-opacity = 0.85;
active-opacity = 1.0;

# --- إلغاء التأثيرات ---
# تم إلغاء الظلال، الوميض، والـ blur تماماً
shadow = false;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
blur = false;

opacity-rule = [
  "90:class_g = 'Xfce4-terminal'",
  "90:class_g = 'kitty'"
];
